use_frameworks!

target 'SSLocalNotification_Example' do
  pod 'SSLocalNotification', :path => '../'

  target 'SSLocalNotification_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
